# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: CC0-1.0

[profile.ci]
fail-fast = false
[profile.ci.junit]
path = "junit.xml"
store-success-output = true
store-failure-output = true
