# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: CC0-1.0

name: Add issues to Product Management Project.

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/famedly/projects/4
          github-token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT }}
