# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always

# Defined CI jobs.
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: REUSE Compliance check
        uses: fsfe/reuse-action@v5

  check:
    uses: famedly/backend-build-workflows/.github/workflows/rust-workflow.yml@v1
    secrets: inherit
    with:
      clippy_args: "--all-features"
      test_args: "--all-features"
      testcov_args: "--all-features"
