# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always

# Defined CI jobs.
jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5
      - name: Dependency license check
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check bans licenses sources
  rust:
    needs: compliance
    uses: famedly/backend-build-workflows/.github/workflows/rust-workflow.yml@v2
    secrets: inherit
    with:
      clippy_args: '--all-features'
      test_args: '--all-features'
      testcov_args: '--all-features'
      ref: v2

  publish:
    needs: rust
    uses: famedly/backend-build-workflows/.github/workflows/publish-crate.yml@v2
    with:
      registry-name: "crates-io"
      registry-index: "https://github.com/rust-lang/crates.io-index"
    secrets:
      CI_SSH_PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
      registry-auth-token: ${{ secrets.CRATES_IO_TOKEN }}
